### ISSUE TITLE
[Backlog] 타임리프를 통한 페이지 구축

### ISSUE THREAD

**Issue by MeteorLee** [private-project-shopping-mall/shopping-mall#13]
## Description

타임리프를 추가하여 페이지 구축
부트스트랩 이용

## Tasks

- [x] 타임리프 적용
- [x] 타임리프 기본 예제 실습
- [x] 타임리프 레이아웃 적용
- [x] 부트스트랩을 이용한 header, footer 구축

## References

- [부트스트랩](https://getbootstrap.kr/)
