### ISSUE TITLE
[Backlog] 연관 관계 매핑

### ISSUE THREAD

**Issue by MeteorLee** [private-project-shopping-mall/shopping-mall#28]
## Description

연관 관계 매핑 종류 연습

## Tasks

- [ ] 일대일 단방향 매핑
- [ ] 다대앨 단방향 매핑
- [ ] 다대일/일대다 양방향 매핑
- [ ] 다대다 매핑
